FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    build-essential \
    git \
    vim \
    curl \
    sudo \
    && apt clean \
	&& git clone https://github.com/turkosaurus/dotfiles

# Create a non-root user 'dev' with sudo privileges
RUN useradd -m -s /bin/bash dev && \
    echo "dev ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER dev
WORKDIR /home/dev

CMD ["bash"]
