#!/usr/bin/env bash

GO_VERSION="1.23.0"
TARBAL_NAME="go$GO_VERSION.linux-amd64.tar.gz"
GO_DL=https://go.dev/dl/"$TARBAL_NAME"

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

if go version; then
    echo "Go installed: $(go version)"
    exit 0
fi

wget -O $TARBAL_NAME $GO_DL
rm -rf /usr/local/go && tar -C /usr/local -xzf $TARBAL_NAME
rm -rf $TARBAL_NAME

# update path
SHELL_RC=".bashrc"
inPATH=$(grep -c ":usr/local/go/bin" "$SHELL_RC")
if [ ! $inPATH -gt 0 ]; then
    echo "export PATH=$PATH:/usr/local/go/bin" >> "$SHELL_RC"
    export PATH=$PATH:/usr/local/go/bin
else
    echo "Go path is set."
fi

if go version; then
    echo Installed: $(go version)
    exit 0
else
    echo "Failed to install go. :("
    exit 1
fi
